sudo: required
services:
  - docker

before_install:
  - docker build -t ahuang757/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ahuang757/react-test npm test -- --coverage

after_success:
  - docker build -t ahuang757/multi-client ./client
  - docker build -t ahuang757/multi-server ./server
  - docker build -t ahuang757/multi-nginx ./nginx
  - docker build -t ahuang757/multi-worker ./worker
  # Log in to the docker CLI and get the login credentials from Travis CI environment variables
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ahuang757/multi-client
  - docker push ahuang757/ulti-nginx
  - docker push ahuang757/multi-server
  - docker push ahuang757/multi-worker
